name: UKBinCollectionData Sync

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run_uk_bin_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v3

      - name: Checkout UKBinCollectionData Repo
        uses: actions/checkout@v3
        with:
          repository: 'robbrad/UKBinCollectionData'
          path: 'uk_bin_repo'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install UKBin Dependencies
        run: |
          cd uk_bin_repo
          pip install .
          pip install -r requirements.txt

      - name: Run Central Bedfordshire Scraper
        run: |
          # We run the UKBin module directly
          # Using postcode SG17 5SE
          python uk_bin_repo/uk_bin_collection/uk_bin_collection/collect_data.py CentralBedfordshireCouncil "https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days" -p "SG17 5SE" > bin_data.json

      - name: Commit and Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bin_data.json
          git commit -m "Sync with UKBinCollectionData" || exit 0
          git push
