name: UKBinCollectionData Sync

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run_uk_bin_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v4

      - name: Checkout UKBinCollectionData Repo
        uses: actions/checkout@v4
        with:
          repository: 'robbrad/UKBinCollectionData'
          path: 'uk_bin_repo'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install UKBin Package
        run: |
          cd uk_bin_repo
          pip install .

      - name: Run Central Bedfordshire Scraper
        run: |
          # Adding the specific internal path to PYTHONPATH
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/uk_bin_repo/uk_bin_collection"
          
          # Running the module with the full path to the council scraper
          python -m uk_bin_collection.collect_data CentralBedfordshireCouncil "https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days" -p "SG17 5SE" > bin_data.json

      - name: Commit and Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bin_data.json
          git commit -m "Sync with UKBinCollectionData" || exit 0
          git push
